version: "3"
services:
  web:
    build:
      context: ./node-app
      dockerfile: Dockerfile.dev
    ports:
      - "1506:1506"

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
