name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: scp file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SERVER_SSH_KEY}}
          port: 22
          source: "."
          target: "~/server/"

      # - name: Zip source
      #   run: |
      #     zip -r node-app.zip node-app

      # - name: scp file dist.zip to server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{secrets.SERVER_HOST}}
      #     username: ${{secrets.SERVER_USERNAME}}
      #     key: ${{secrets.SERVER_SSH_KEY}}
      #     port: 22
      #     source: "./node-app.zip"
      #     target: "~/server/"

      # - name: unzip source
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{secrets.SERVER_HOST}}
      #     username: ${{secrets.SERVER_USERNAME}}
      #     key: ${{secrets.SERVER_SSH_KEY}}
      #     port: 22
      #     script: |
      #       mkdir -p node-app
      #       cd ~/server/
      #       sudo rm -rf node-app
      #       unzip -o node-app.zip

      - name: SSH into the server and run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ~/server/
            sudo docker compose up -d
